### ISSUE TITLE
Python doesn't support %s as an argument to strftime

### ISSUE THREAD

**Issue by ryavorsky** [yutkin/VK-Top#1]
The bug is here:

```
def recieve_posts(page_id, last_days, reposts):
    deadline = datetime.now() - timedelta(days=last_days)
    unix_stamp = int(deadline.strftime("%s"))

```

See http://stackoverflow.com/questions/11743019/convert-python-datetime-to-epoch-with-strftime

**Comment by yutkin** [comment]
Thank you for feedback! Fixed in https://github.com/yutkin/VK-Top/commit/9277be452b203f420b653ed2761747e9fdb435d8.
