### ISSUE TITLE
Access token error

### ISSUE THREAD

**Issue by koorool** [yutkin/VK-Top#2]
VK API Response with following error:

> vk api error: Invalid request: method is unavailable without access token

![image](https://user-images.githubusercontent.com/5508137/28006417-de84b384-6557-11e7-8fb0-abaddd4c5f46.png)

**Comment by yutkin** [comment]
@koorool, thank you for bug report! Bug has been fixed in 16f2db645b6c45d13ea7ca4b36ab128699ecd473.
