### ISSUE TITLE
vk api error: Too many requests per second

### ISSUE THREAD

**Issue by uenro** [yutkin/VK-Top#3]
/Library/Frameworks/Python.framework/Versions/2.7/bin/vktop: vk api error: Too many requests per second
I guess it's because of new vk api limitations
Also, maybe it's better to use execute method?

**Comment by yutkin** [comment]
Could you, please, provide arguments that you have used for running?

**Comment by uenro** [comment]
vktop https://vk.com/ditaredrum --top 10

**Comment by yutkin** [comment]
Fixed in v2.4
